apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front-back-end
  name: front-back-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-back-end
  strategy: {}
  template:
    metadata:
      labels:
        app: front-back-end
    spec:
      containers:
      - image: nginx
        name: nginx
        env:
        - name: db_user
          valueFrom:
            secretKeyRef: 
              name: db-creds
              key: db_user
        - name: db_password
          valueFrom:
            secretKeyRef: 
              name: db-creds
              key: db_password
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        resources: {}
      volumes:
        - name: config-volume
          configMap:
            name: ui-config
status: {}
