apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secret-test
  name: secret-test
spec:
  containers:
  - image: nginx
    name: secret-test
    resources: {}
    volumeMounts:
    - name: foo
      readOnly: true
      mountPath: "/etc/foo"
  volumes: 
    - name: foo
      secret:
        secretName: my-api-key
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
